GET http://127.0.0.1:8000/api/products
Authorization: Bearer 1|El0stuxdOyR5ZpW9rjhzCR0y2kNWWEN8UrGBegnE8368cf29
Accept: application/json
###

POST http://127.0.0.1:8000/api/products
Authorization: Bearer 1|El0stuxdOyR5ZpW9rjhzCR0y2kNWWEN8UrGBegnE8368cf29
Content-Type: application/json
Accept: application/json

{
  "nombre": "Bicicleta estática",
  "descripcion": "Bicicleta para entrenamiento cardiovascular en casa",
  "precio": 299.99
}
###


GET http://127.0.0.1:8000/api/products/17
Authorization: Bearer 1|El0stuxdOyR5ZpW9rjhzCR0y2kNWWEN8UrGBegnE8368cf29
Accept: application/json
###

PUT http://127.0.0.1:8000/api/products/17
Authorization: Bearer 1|El0stuxdOyR5ZpW9rjhzCR0y2kNWWEN8UrGBegnE8368cf29
Content-Type: application/json
Accept: application/json

{
  "precio": 279.99
}
###

DELETE http://127.0.0.1:8000/api/products/4
Authorization: Bearer 1|El0stuxdOyR5ZpW9rjhzCR0y2kNWWEN8UrGBegnE8368cf29
Accept: application/json

###

POST http://127.0.0.1:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email":"mikel@prueba2.es",
    "password":"mikelito123"
}

###
POST http://127.0.0.1:8000/api/logout
Accept: application/json
Authorization: Bearer 17|fSfhrdrueFXXjDbiZvDD13QSyxZoB62ET6mdJ4yYe137ac13

###
POST http://127.0.0.1:8000/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "Mikel Arroyo",
    "email": "mikel@prueba4.es",
    "password": "mikelito123"
}

